### ISSUE TITLE
接入taro报错

### ISSUE THREAD

**Issue by Varavarforvar** [FaureWu/zoro#1]
```
thirdScriptError 
 sdk uncaught third Error 
 Cannot read property 'prototype' of undefined 
 TypeError: Cannot read property 'prototype' of undefined
    at runInContext (http://127.0.0.1:53914/appservice/npm/lodash/lodash.js:1435:27)
    at http://127.0.0.1:53914/appservice/npm/lodash/lodash.js:17078:11
    at http://127.0.0.1:53914/appservice/npm/lodash/lodash.js:17105:3
    at require (http://127.0.0.1:53914/appservice/__dev__/WAService.js:22:3705)
    at http://127.0.0.1:53914/appservice/__dev__/WAService.js:22:3419
    at http://127.0.0.1:53914/appservice/npm/zoro/zoro.js:1:271
    at require (http://127.0.0.1:53914/appservice/__dev__/WAService.js:22:3705)
    at http://127.0.0.1:53914/appservice/__dev__/WAService.js:22:3419
    at http://127.0.0.1:53914/appservice/app.js:15:13
    at require (http://127.0.0.1:53914/appservice/__dev__/WAService.js:22:3705)
```

**Comment by anddo** [comment]
在尝试编译百度小程序的时候出现了相同的错误，请问怎么解决的？
